#include "radeon_legacy.h"
#include <stdlib.h>
#if defined(RLG_HAVE_VULKAN)
#include <vulkan/vulkan.h>
struct RLGHost{VkInstance instance;VkPhysicalDevice physical;VkDevice device;VkQueue queue;uint32_t qfam;VkCommandPool pool;};
int rlg_host_init(RLGDevice*d){if(!d)return-1;RLGHost*h=calloc(1,sizeof(*h));if(!h)return-2;VkApplicationInfo ai={.sType=VK_STRUCTURE_TYPE_APPLICATION_INFO,.pApplicationName="radeon-legacy-vgpu",.applicationVersion=VK_MAKE_VERSION(0,3,0),.pEngineName="R300/R500 translation backend",.engineVersion=VK_MAKE_VERSION(0,3,0),.apiVersion=VK_API_VERSION_1_1};VkInstanceCreateInfo ici={.sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,.pApplicationInfo=&ai};if(vkCreateInstance(&ici,NULL,&h->instance)!=VK_SUCCESS)goto fail;uint32_t n=0;if(vkEnumeratePhysicalDevices(h->instance,&n,NULL)!=VK_SUCCESS||!n)goto fail;VkPhysicalDevice*pd=calloc(n,sizeof(*pd));if(!pd)goto fail;vkEnumeratePhysicalDevices(h->instance,&n,pd);h->physical=pd[0];free(pd);uint32_t qn=0;vkGetPhysicalDeviceQueueFamilyProperties(h->physical,&qn,NULL);VkQueueFamilyProperties*qp=calloc(qn,sizeof(*qp));if(!qp)goto fail;vkGetPhysicalDeviceQueueFamilyProperties(h->physical,&qn,qp);int q=-1;for(uint32_t i=0;i<qn;++i)if(qp[i].queueFlags&VK_QUEUE_GRAPHICS_BIT){q=(int)i;break;}free(qp);if(q<0)goto fail;h->qfam=(uint32_t)q;float pr=1.0f;VkDeviceQueueCreateInfo qci={.sType=VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,.queueFamilyIndex=h->qfam,.queueCount=1,.pQueuePriorities=&pr};VkDeviceCreateInfo dci={.sType=VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,.queueCreateInfoCount=1,.pQueueCreateInfos=&qci};if(vkCreateDevice(h->physical,&dci,NULL,&h->device)!=VK_SUCCESS)goto fail;vkGetDeviceQueue(h->device,h->qfam,0,&h->queue);VkCommandPoolCreateInfo pci={.sType=VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,.queueFamilyIndex=h->qfam};if(vkCreateCommandPool(h->device,&pci,NULL,&h->pool)!=VK_SUCCESS)goto fail;d->host=h;return 0;fail:if(h->device)vkDestroyDevice(h->device,NULL);if(h->instance)vkDestroyInstance(h->instance,NULL);free(h);return-3;}
void rlg_host_destroy(RLGDevice*d){if(!d||!d->host)return;RLGHost*h=d->host;if(h->device){vkDeviceWaitIdle(h->device);if(h->pool)vkDestroyCommandPool(h->device,h->pool,NULL);vkDestroyDevice(h->device,NULL);}if(h->instance)vkDestroyInstance(h->instance,NULL);free(h);d->host=NULL;}
bool rlg_host_is_active(const RLGDevice*d){return d&&d->host;}
#else
struct RLGHost{int unused;};int rlg_host_init(RLGDevice*d){(void)d;return-1;}void rlg_host_destroy(RLGDevice*d){if(d)d->host=NULL;}bool rlg_host_is_active(const RLGDevice*d){return d&&d->host;}
#endif
